export const dataToTest = [
    { id: 1, name: 'Mr Nice', description: 'Guau what a nice man', metadata: { clave: 'valor', clave2: 'valor2' } },
    { id: 2, name: 'Marco', description: 'Polo', metadata: { clave: 'valor', clave2: 'valor2' } },
    { id: 3, name: 'Bombastico', description: 'Increibles vocablos', metadata: { clave: 'valor', clave2: 'valor2' } },
    { id: 4, name: 'Celeritas 2', description: ': la venganza', metadata: { clave: 'valor', clave2: 'valor2' } },
    { id: 5, name: 'Magneto', description: 'nunca se deja las lentejas', metadata: { clave: 'valor', clave2: 'valor2' } },
    { id: 6, name: 'RubberWoman', description: 'increibles contorsiones que puede hacer la señora', metadata: { clave: 'valor', clave2: 'valor2' } },
    { id: 7, name: 'Dynamo', description: 'Si te descuidas te carga la batería del coche', metadata: { clave: 'valor', clave2: 'valor2' } },
    { id: 8, name: 'Dr -IQ', description: 'Oh no, no entiende los chistes de Rick y Morty', metadata: { clave: 'valor', clave2: 'valor2' } },
    { id: 9, name: 'Magmatron', description: 'Este señor está muy OP', metadata: { clave: 'valor', clave2: 'valor2' } },
    { id: 10, name: 'Huracan', description: 'A veces los señores de EEUU le disparan', metadata: { clave: 'valor', clave2: 'valor2' } },
    { id: 11, name: 'Dr Nice', description: 'A nice man with a doctorado', metadata: { clave: 'valor', clave2: 'valor2' } },
    { id: 12, name: 'Narco', description: 's no la he visto, pero dicen que está bien', metadata: { clave: 'valor', clave2: 'valor2' } },
    { id: 13, name: 'Bombasto', description: 'bombástico!', metadata: { clave: 'valor', clave2: 'valor2' } },
    { id: 14, name: 'Celeritas', description: 'no se que significa su nombre jaja salu2', metadata: { clave: 'valor', clave2: 'valor2' } },
    { id: 15, name: 'Magneta', description: 'la mujer de magneta', metadata: { clave: 'valor', clave2: 'valor2' } },
    { id: 16, name: 'RubberMan', description: 'el hombre de goma. No se estira, solo borra cosas', metadata: { clave: 'valor', clave2: 'valor2' } },
    { id: 17, name: 'Dynama', description: 'la mujer de dynamó', metadata: { clave: 'valor', clave2: 'valor2' } },
    { id: 18, name: 'Dr IQ', description: 'omg puede reirse viendo rick y morty', metadata: { clave: 'valor', clave2: 'valor2' } },
    { id: 19, name: 'Magma', description: 'magmatron colega', metadata: { clave: 'valor', clave2: 'valor2' } },
    { id: 20, name: 'Tornado', description: 'el hermano pequeño de huracán', metadata: { clave: 'valor', clave2: 'valor2' } },
];